services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=security_oauth2
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db-data:
    driver: local